OOP school library: add basic UI
luccamicale/OOP-Library-School pull request #4
Opened 2023-01-06 01:00 UTC by luccamicale

## School Library Basic UI 💯 

##https://github.com/luccamicale/OOP-Library-School 👍 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] Created app.rb and main.rb files
- [ ] Created methods to:
      List all books.
      List all people.
      Create a person (teacher or student, not a plain Person).
      Create a book.
      Create a rental.
      List all rentals for a given person id.
- [ ] Added an interface class 🔢 🥇

2023-01-06 17:14 UTC, vickymarz requested changes
Hi @luccamicale, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that does not contain the `future-feature` section in your readme. Kindly add at least 2 future features you will potentially add to your project in the `future-feature` section of your readme 👍🏽 

- I will also recommend you also always capitalize the first letter of your commit messages and it should be written in the imperative form. e.g `Add book.rb file`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-06 17:39 UTC, luccamicale commented
Hi @vickymarz I modified the readme. Now I added this part that you ask me.

2023-01-06 19:15 UTC, jasonfelice requested changes
Hi @luccamicale, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
No Linter Errors✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 19:15 UTC, jasonfelice commented on app.rb
> +  def list_all_books
- [ ] Kindly fix the following error on List all Books

![image](https://user-images.githubusercontent.com/92215878/211083053-6ca15ac2-5e00-47b5-b201-c659b3a91010.png)

2023-01-06 19:15 UTC, jasonfelice commented on app.rb
> +  def list_all_people
- [ ] Same error on List all People. Please fix this error. 😄

![image](https://user-images.githubusercontent.com/92215878/211083224-f0c7e4a3-6fdd-4ed9-bcfe-84d7f548e927.png)

2023-01-06 20:45 UTC, luccamicale commented
Hi @jasonfelice I dont understand how to solve that. Can you help me please?

2023-01-06 23:13 UTC, luccamicale commented
I fix the two errors in my code. the method is the same in the file main and app. Now my project should be approved!!! 💯 👍 🔢

2023-01-06 23:26 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Lucca,
### Great work on making the changes requested by a previous reviewer 👏 
### You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
## To Highlight 🎉
No linter errors. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-06 23:26 UTC, SajjadAhmad14 commented on app.rb
> +  def list_all_people
Good job on making the progress! But there is still an error when user tries to list all people. Kindly see the error and fix it.

![people](https://user-images.githubusercontent.com/35504149/211116179-84e9b57f-e7ec-42ec-a588-2cc174756dea.png)

2023-01-07 01:11 UTC, luccamicale commented
I fix the only problem. the last reviewer help me with the problem and told me that removing the person.type the problem it is solve. Now my project should be approved!!!! 💯 🥇

2023-01-07 01:33 UTC, mwanawabangona approved these changes
Hi @luccamicale,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good  job implementing the requested chnges!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 02:05 UTC, merged